### ISSUE TITLE
API Call to ERPNext Failed

### ISSUE THREAD

**Issue by farukahmmed** [frappe/biometric-attendance-sync-tool#37]
2022-10-29 16:08:02,248	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "172.16.16.219", "punch_direction": "", "clear_from_device_on_fetch": ""}
Traceback (most recent call last):
  File "C:\biometric-attendance-sync-tool-v1.0-win64\biometric-attendance-sync-tool-v1.0-win64\erpnext_sync.py", line 51, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "C:\biometric-attendance-sync-tool-v1.0-win64\biometric-attendance-sync-tool-v1.0-win64\erpnext_sync.py", line 129, in pull_process_and_push_data
    raise Exception('API Call to ERPNext Failed.')
Exception: API Call to ERPNext Failed.
2022-10-29 16:09:03,328	ERROR	Error during ERPNext API Call.	2	1667018015.0	1		Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 72, in execute_cmd
    method = get_attr(cmd)
  File "apps/frappe/frappe/handler.py", line 258, in get_attr
    method = frappe.get_attr(cmd)
  File "apps/frappe/frappe/__init__.py", line 1575, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.hr.doctype.employee_checkin.employee_checkin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 74, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Failed to get method for command erpnext.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field with No module named 'erpnext.hr.doctype.employee_checkin.employee_checkin'

2022-10-29 16:09:03,328	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "172.16.16.219", "punch_direction": "", "clear_from_device_on_fetch": ""}
Traceback (most recent call last):
  File "C:\biometric-attendance-sync-tool-v1.0-win64\biometric-attendance-sync-tool-v1.0-win64\erpnext_sync.py", line 51, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "C:\biometric-attendance-sync-tool-v1.0-win64\biometric-attendance-sync-tool-v1.0-win64\erpnext_sync.py", line 129, in pull_process_and_push_data
    raise Exception('API Call to ERPNext Failed.')
Exception: API Call to ERPNext Failed.

**Comment by karthikeyan5** [comment]
Fixed in PR #35 
Please update your script to the latest version and add the key as mentioned in [this comment](https://github.com/frappe/biometric-attendance-sync-tool/issues/32#issuecomment-1295868786).
