### ISSUE TITLE
Getting error while fetching data from device

### ISSUE THREAD

**Issue by farukahmmed** [frappe/biometric-attendance-sync-tool#39]
2022-11-17 15:17:04,430	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "172.16.16.51", "punch_direction": null, "clear_from_device_on_fetch": false}
Traceback (most recent call last):
  File "C:\biometric-attendance-sync-tool\venv\lib\site-packages\zk\base.py", line 248, in __send_command
    self.__sock.send(top)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "erpnext_sync.py", line 148, in get_all_attendance_from_device
    conn = zk.connect()
  File "C:\biometric-attendance-sync-tool\venv\lib\site-packages\zk\base.py", line 373, in connect
    cmd_response = self.__send_command(const.CMD_CONNECT)
  File "C:\biometric-attendance-sync-tool\venv\lib\site-packages\zk\base.py", line 260, in __send_command
    raise ZKNetworkError(str(e))
zk.exception.ZKNetworkError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "erpnext_sync.py", line 61, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "erpnext_sync.py", line 88, in pull_process_and_push_data
    device_attendance_logs = get_all_attendance_from_device(device['ip'], device_id=device['device_id'], clear_from_device_on_fetch=device['clear_from_device_on_fetch'])
  File "erpnext_sync.py", line 169, in get_all_attendance_from_device
    raise Exception('Device fetch failed.')
Exception: Device fetch failed.

**Comment by karthikeyan5** [comment]
https://discuss.erpnext.com/t/connection-zkteco-with-erpnext/52915/7?u=karthikeyan5

please refer to this and post further questions in the forum.

**Comment by karthikeyan5** [comment]
@farukahmmed, please do a minimum of a google search to find solutions to your problem before asking for help or creating an issue. It saves you as well as others a lot of time.
