### ISSUE TITLE
API Call to ERPNext Failed.

### ISSUE THREAD

**Issue by Hunt16** [frappe/biometric-attendance-sync-tool#46]
ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "192.168.100.201", "punch_direction": "AUTO", "clear_from_device_on_fetch": ""}
Traceback (most recent call last):
  File "erpnext_sync.py", line 51, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "erpnext_sync.py", line 129, in pull_process_and_push_data
    raise Exception('API Call to ERPNext Failed.')
Exception: API Call to ERPNext Failed.

**Comment by Mohd200** [comment]
Hello @karthikeyan5 @Anurag810 @KaviyaPeriyasamy @surajshetty3416 @rtdany10 

I am facing the same Problem, the ('API Call to ERPNext Failed.')

I created a new User with HR Manager Role and generated API Secret and Key, and placed the Primary URL of ERPNext and still getting this error message:
----
2023-03-21 18:03:06,843	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "10.51.114.143", "punch_direction": "AUTO", "clear_from_device_on_fetch": ""}
Traceback (most recent call last):
  File "C:\Users\mhmd-\OneDrive\Desktop\Output\Bio-metric sync tool\biometric-attendance-sync-tool-v1.0-win32\erpnext_sync.py", line 51, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "C:\Users\mhmd-\OneDrive\Desktop\Output\Bio-metric sync tool\biometric-attendance-sync-tool-v1.0-win32\erpnext_sync.py", line 129, in pull_process_and_push_data
    raise Exception('API Call to ERPNext Failed.')
Exception: API Call to ERPNext Failed.

Please advice on how to reconnect the Biometric-attendance-sync-tool to the ERPNext.

**Comment by Mohd200** [comment]
Hello everyone and Good day

It turned out that I registered a new Fingerprint in the device and didn't link the User ID to an Employee HR Profile in the ERPNext.
Once I put the user ID in the Employee HR Profile it worked immediately.
However, this raise an issue, what if I need to add a new Fingerprint of a person that isn't an Employee to the Biometric Device?
The connection will definitely crash again.

@karthikeyan5 @Anurag810 @KaviyaPeriyasamy @surajshetty3416 @rtdany10 
Please advise

**Comment by elhananjair** [comment]
Ok, for anyone facing the same issue, I am using Caddy as a reverse proxy and local HTTPS for ERPNext, and I needed to add the root.pem to the trusted local store. That was the reason, after I did that, I got another issue, which is 
```
frappe.exceptions.ValidationError: Latitude and longitude values are required for checking in.
```
This error is caused because of "**Allow Geolocation Tracking**" HR Settings. After I disabled that, all employee checking was fetched.
