### ISSUE TITLE
API call Failed

### ISSUE THREAD

**Issue by NayanGajjar** [frappe/biometric-attendance-sync-tool#47]
getting below error

2023-04-12 16:46:16,561 ERROR Error during ERPNext API Call. 617 1677643252.0 Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 66, in application
response = frappe.api.handle()
File "apps/frappe/frappe/api.py", line 54, in handle
return frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 45, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/init.py", line 1607, in call
return fn(*args, **newargs)
TypeError: add_log_based_on_employee_field() missing 2 required positional arguments: 'employee_field_value' and 'timestamp'

[url we using:](https://frappehr.com/docs/v14/user/manual/en/setting-up/articles/integrating-erpnext-with-biometric-attendance-devices#2-populating-the-biometric-punch-logs-into-erpnexts-employee-checkin)

the API mentioned in the given documents is an old one.. the new API we are calling is api/method/hrms.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field

Module
HR

Version
ERPNext: v14.20.3 (HEAD)

Frappe Framework: v14.31.0 (version-14)

Frappe HR: v14.2.1 (HEAD)

**Comment by ruchamahabal** [comment]
Addressed here
https://github.com/frappe/hrms/issues/442
