### ISSUE TITLE
Unauthenticated Issue

### ISSUE THREAD

**Issue by precihole** [frappe/biometric-attendance-sync-tool#50]
2023-06-01 15:14:28,198	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "2", "ip": "192.158.1.50", "punch_direction": null, "clear_from_device_on_fetch": false}
Traceback (most recent call last):
  File "C:\Users\rehan\OneDrive\Desktop\biometric-attendance-sync-tool-master-papl\erpnext_sync.py", line 149, in get_all_attendance_from_device
    conn = zk.connect()
           ^^^^^^^^^^^^
  File "C:\Users\rehan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\zk\base.py", line 384, in connect
    raise ZKErrorResponse("Unauthenticated")
zk.exception.ZKErrorResponse: Unauthenticated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rehan\OneDrive\Desktop\biometric-attendance-sync-tool-master-papl\erpnext_sync.py", line 62, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "C:\Users\rehan\OneDrive\Desktop\biometric-attendance-sync-tool-master-papl\erpnext_sync.py", line 89, in pull_process_and_push_data
    device_attendance_logs = get_all_attendance_from_device(device['ip'], device_id=device['device_id'], clear_from_device_on_fetch=device['clear_from_device_on_fetch'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rehan\OneDrive\Desktop\biometric-attendance-sync-tool-master-papl\erpnext_sync.py", line 170, in get_all_attendance_from_device
    raise Exception('Device fetch failed.')
Exception: Device fetch failed.

**Comment by precihole** [comment]
It is solved by setting Comm key as 0
