### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by falahtech** [frappe/biometric-attendance-sync-tool#63]
When I run command `python3 erpnext_sync.py` its showing below error.

> Traceback (most recent call last):
>   File "/home/sigma/frappe-bench/biometric-attendance-sync-tool/erpnext_sync.py", line 319, in <module>
>     status = pickledb.load('/'.join([config.LOGS_DIRECTORY, 'status.json']), True)
>   File "/home/sigma/frappe-bench/biometric-attendance-sync-tool/venv/lib/python3.10/site-packages/pickledb.py", line 43, in load
>     return PickleDB(location, auto_dump, sig)
>   File "/home/sigma/frappe-bench/biometric-attendance-sync-tool/venv/lib/python3.10/site-packages/pickledb.py", line 54, in __init__
>     self.load(location, auto_dump)
>   File "/home/sigma/frappe-bench/biometric-attendance-sync-tool/venv/lib/python3.10/site-packages/pickledb.py", line 85, in load
>     self._loaddb()
>   File "/home/sigma/frappe-bench/biometric-attendance-sync-tool/venv/lib/python3.10/site-packages/pickledb.py", line 102, in _loaddb
>     self.db = json.load(open(self.loco, 'rt'))
>   File "/usr/lib/python3.10/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by suhailmdcse** [comment]
```
with open("/path/to/file_name.json", 'ar+') as f:
        param_json = json.load(f)
```
No, the mode 'ar+' is not valid in Python 3. In Python 3, valid modes for the open() function include:

    'r': read
    'w': write (overwriting the file)
    'a': append
    'b': binary mode
    '+': update (read/write)
```
with open("/path/to/file_name.json", 'a+') as f:
        param_json = json.load(f)
```
